spring.application.name = retailBillingSoftware

#Database property
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

#Context path
#in future if we update the api we can change the version in below
server.servlet.context-path =/api/v1.0

#Cloudinary_Props
cloudinary.cloud_name=your_cloudinary_name
cloudinary.api_key=your_cloudinary_api
cloudinary.api_secret=your_cloudinary_secret

#JWT
jwt.secret.key=thisismysecretkeyfortheupcomingproject

#below id's are not mine. Use your own ID
razorpay.key.id = your_razorpay_id
razorpay.key.secret = your_razorpay_key


# Increase the max file size (individual file)
spring.servlet.multipart.max-file-size=10MB
# Increase the max request size (file + JSON data)
spring.servlet.multipart.max-request-size=10MB
